"""about author column added up

Revision ID: 387886ff40f3
Revises: 88fd938cb06f
Create Date: 2024-04-13 12:14:13.867318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387886ff40f3'
down_revision = '88fd938cb06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
